### PR TITLE
Updating eventing-contrib kafka operator

### PR DESCRIPTION
**Pull request by alanconway**
Following steps in https://jira.coreos.com/browse/SRVKE-175.

### CODE REVIEW

**Comment by lberk** [comment]
@alanconway I'm not sure, it works for me?
```
% operator-sdk olm-catalog gen-csv --update-crds --csv-version 0.9.0 --from-version 0.8.2
INFO[0000] Generating CSV manifest version 0.9.0        
INFO[0000] Created deploy/olm-catalog/knative-kafka-operator/0.9.0/knative-kafka-operator.v0.9.0.clusterserviceversion.yaml
```

**Comment by matzew** [comment]
@alanconway we need to have the channel _and_ the source yamls. As said on slack, let;s rename the file to `kafka-channel-v0.9.0.yaml` and `kafka-source-v0.9.0.yaml`.

also, the go code - for the channel needs to be updated, like said in the JIRA for this.

what version of the sdk do you use ? looks like for Lukas it did work?

**Comment by lberk** [comment]
https://github.com/lberk/knative-kafka-operator/tree/090-kafka-csv for reference, here's my generated csv from your branch

**Comment by lberk** [comment]
@matzew I think @alanconway combined both resource files into a single resource?

**Comment by alanconway** [comment]
@lberk @matzew 
$ operator-sdk version
operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"

I didn't combine or split any files, I copied the existing file

    knative.dev/eventing-contrib/openshift/release/knative-eventing-kafka-contrib-v0.9.0.yaml

I'd rather not rename files unless it is necessary. It already is quite hard for a newcomer to understand which files to copy/delete/cut-and-paste from where to where. If we rename the files as well it becomes even harder.

**Comment by alanconway** [comment]
All good. I was using the latest 0.11.0 operator-sdk, I regressed back to 0.8.0 (version of the vendored libs) and it works fine.

**Comment by alanconway** [comment]
/hold
Need to update the channel go code as @matzew said in https://github.com/openshift-knative/knative-kafka-operator/pull/33#issuecomment-546026625

**Comment by alanconway** [comment]
/hold release
Hopefully good to go

**Comment by matzew** [comment]
> I'd rather not rename files unless it is necessary. It already is quite hard for a newcomer to understand which files to copy/delete/cut-and-paste from where to where. If we rename the files as well it becomes even harder.

Upstream did rename those too, to channel and source (before was CCP and importer etc).  IMO it;s just simpler if you have two files, one that says "source", and one that says "channel", to guess what's actually inside of that file.

And I expect upstream to stick w/ these names, so we match what they have.

**Comment by alanconway** [comment]
> > I'd rather not rename files unless it is necessary. It already is quite hard for a newcomer to understand which files to copy/delete/cut-and-paste from where to where. If we rename the files as well it becomes even harder.
> 
> Upstream did rename those too, to channel and source (before was CCP and importer etc). IMO it;s just simpler if you have two files, one that says "source", and one that says "channel", to guess what's actually inside of that file.

Agreed but consistency is also important. I copied this "upstream" file: 

    knative.dev/eventing-contrib/openshift/release/knative-eventing-kafka-contrib-v0.9.0.yaml

Did I copy the wrong file? 

I'd be happy to copy separate files if they're separate from beginning to end, but I'm not  keen on manually-copied files changing name or splitting/joining in the middle of the process. Do we need to change some generators further up to generate 2 files?

**Comment by matzew** [comment]
> I copied this "upstream" file:

with `openshift` in the name, we are not having an upstream file. Upstream means community's knative release.  

OK, what I am saying is that the `deploy/resources` folder should contain these two files:
* https://github.com/knative/eventing-contrib/releases/download/v0.9.0/kafka-channel.yaml
* https://github.com/knative/eventing-contrib/releases/download/v0.9.0/kafka-source.yaml

and... historically, in our "midstream" operators (for sefving, build (back in the day), eventing), we had some convention to sponsor a version string in the file name, like:

* `kafka-channel-v0.9.0.yaml`
* `kafka-source-v0.9.0.yaml`

**Comment by matzew** [comment]
I will do it for now :-)

**Comment by alanconway** [comment]
> I will do it for now :-)

Phew!

**Pull request merged**
